//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dthurn/Dropbox/firebase/objc-test/ca/thurn/testing/SharedTestCase.java
//
//  Created by dthurn on 12/8/13.
//

#ifndef _CaThurnTestingSharedTestCase_H_
#define _CaThurnTestingSharedTestCase_H_

@class CaThurnTestingSharedTestCase_TestModeEnum;
@class JavaUtilConcurrentAtomicAtomicBoolean;
@class JavaUtilConcurrentAtomicAtomicInteger;

#import "JreEmulation.h"
#include "java/lang/Enum.h"
#include "java/lang/Runnable.h"
#include "java/util/TimerTask.h"
#include "junit/framework/TestCase.h"

@interface CaThurnTestingSharedTestCase : JunitFrameworkTestCase {
 @public
  JavaUtilConcurrentAtomicAtomicBoolean *didSetUpTestCase_;
}

- (NSString *)getJavascriptModuleName;
+ (void)runMainWithNSString:(NSString *)name;
- (void)setUp;
- (void)tearDown;
- (void)sharedSetUpTestCaseWithJavaLangRunnable:(id<JavaLangRunnable>)done;
- (void)sharedSetUpWithJavaLangRunnable:(id<JavaLangRunnable>)done;
- (void)sharedTearDown;
- (void)injectScriptWithNSString:(NSString *)url
            withJavaLangRunnable:(id<JavaLangRunnable>)onComplete;
- (void)beginAsyncTestBlock;
- (void)beginAsyncTestBlockWithInt:(int)numFinishesExpected;
- (void)endAsyncTestBlock;
- (CaThurnTestingSharedTestCase_TestModeEnum *)getTestMode;
- (void)finished;
- (void)scheduleWithInt:(int)delayMillis
   withJavaLangRunnable:(id<JavaLangRunnable>)runnable;
- (int)randomInteger;
- (void)assertDeepEqualsWithId:(id)o1
                        withId:(id)o2;
- (void)assertDeepEqualsWithNSString:(NSString *)msg
                              withId:(id)o1
                              withId:(id)o2;
- (id)init;
- (void)copyAllFieldsTo:(CaThurnTestingSharedTestCase *)other;
@end

J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase, didSetUpTestCase_, JavaUtilConcurrentAtomicAtomicBoolean *)

typedef enum {
  CaThurnTestingSharedTestCase_TestMode_JAVA = 0,
  CaThurnTestingSharedTestCase_TestMode_JAVASCRIPT = 1,
  CaThurnTestingSharedTestCase_TestMode_OBJECTIVE_C = 2,
} CaThurnTestingSharedTestCase_TestMode;

@interface CaThurnTestingSharedTestCase_TestModeEnum : JavaLangEnum < NSCopying > {
}
+ (CaThurnTestingSharedTestCase_TestModeEnum *)JAVA;
+ (CaThurnTestingSharedTestCase_TestModeEnum *)JAVASCRIPT;
+ (CaThurnTestingSharedTestCase_TestModeEnum *)OBJECTIVE_C;
+ (IOSObjectArray *)values;
+ (CaThurnTestingSharedTestCase_TestModeEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;
@end

@interface CaThurnTestingSharedTestCase_OneTimeRunnable : NSObject < JavaLangRunnable > {
 @public
  JavaUtilConcurrentAtomicAtomicBoolean *ran_;
  id<JavaLangRunnable> runnable_;
}

- (id)initWithJavaLangRunnable:(id<JavaLangRunnable>)runnable;
- (void)run;
- (void)copyAllFieldsTo:(CaThurnTestingSharedTestCase_OneTimeRunnable *)other;
@end

J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase_OneTimeRunnable, ran_, JavaUtilConcurrentAtomicAtomicBoolean *)
J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase_OneTimeRunnable, runnable_, id<JavaLangRunnable>)

@interface CaThurnTestingSharedTestCase_BooleanReference : NSObject {
 @public
  JavaUtilConcurrentAtomicAtomicBoolean *value_;
}

- (id)initWithBoolean:(BOOL)value;
- (void)setWithBoolean:(BOOL)newValue;
- (BOOL)get;
- (BOOL)getAndSetWithBoolean:(BOOL)newValue;
- (void)copyAllFieldsTo:(CaThurnTestingSharedTestCase_BooleanReference *)other;
@end

J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase_BooleanReference, value_, JavaUtilConcurrentAtomicAtomicBoolean *)

@interface CaThurnTestingSharedTestCase_IntegerReference : NSObject {
 @public
  JavaUtilConcurrentAtomicAtomicInteger *value_;
}

- (id)initWithInt:(int)value;
- (void)setWithInt:(int)newValue;
- (int)get;
- (int)getAndSetWithInt:(int)newValue;
- (int)getAndIncrement;
- (void)copyAllFieldsTo:(CaThurnTestingSharedTestCase_IntegerReference *)other;
@end

J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase_IntegerReference, value_, JavaUtilConcurrentAtomicAtomicInteger *)

@interface CaThurnTestingSharedTestCase_$1 : NSObject < JavaLangRunnable > {
 @public
  CaThurnTestingSharedTestCase *this$0_;
}

- (void)run;
- (id)initWithCaThurnTestingSharedTestCase:(CaThurnTestingSharedTestCase *)outer$;
@end

J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase_$1, this$0_, CaThurnTestingSharedTestCase *)

@interface CaThurnTestingSharedTestCase_$2 : NSObject < JavaLangRunnable > {
 @public
  CaThurnTestingSharedTestCase *this$0_;
  id<JavaLangRunnable> val$runFinished_;
}

- (void)run;
- (id)initWithCaThurnTestingSharedTestCase:(CaThurnTestingSharedTestCase *)outer$
                      withJavaLangRunnable:(id<JavaLangRunnable>)capture$0;
@end

J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase_$2, this$0_, CaThurnTestingSharedTestCase *)
J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase_$2, val$runFinished_, id<JavaLangRunnable>)

@interface CaThurnTestingSharedTestCase_$3 : JavaUtilTimerTask {
 @public
  id<JavaLangRunnable> val$runnable_;
}

- (void)run;
- (id)initWithJavaLangRunnable:(id<JavaLangRunnable>)capture$0;
@end

J2OBJC_FIELD_SETTER(CaThurnTestingSharedTestCase_$3, val$runnable_, id<JavaLangRunnable>)

#endif // _CaThurnTestingSharedTestCase_H_
